DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Employee_Phones CASCADE CONSTRAINTS;
DROP TABLE Employee_Addresses CASCADE CONSTRAINTS;

DROP TABLE Employee_Transfer CASCADE CONSTRAINTS;

DROP TABLE Awards CASCADE CONSTRAINTS;
DROP TABLE Granted_Awards CASCADE CONSTRAINTS;

DROP TABLE Login CASCADE CONSTRAINTS;


DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Calls CASCADE CONSTRAINTS;

DROP TABLE Award_Centers CASCADE CONSTRAINTS;
DROP TABLE Receive_Awards CASCADE CONSTRAINTS;



DROP TABLE Certificate CASCADE CONSTRAINTS;
DROP TABLE Emp_Sales CASCADE CONSTRAINTS;
DROP TABLE Emp_Month_Year CASCADE CONSTRAINTS;
DROP TABLE Transactions CASCADE CONSTRAINTS;


DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Inventories CASCADE CONSTRAINTS;
DROP TABLE Inventory_Products CASCADE CONSTRAINTS;

DROP TABLE Transaction_Products CASCADE CONSTRAINTS;
DROP TABLE Transaction_Increase CASCADE CONSTRAINTS;

DROP TABLE Quota_Offers CASCADE CONSTRAINTS;
DROP TABLE Apply_Offer CASCADE CONSTRAINTS;






